spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: johyeonmin841@gmail.com
    password: zpjvoilqpcorlnmu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  thymeleaf:
    check-template-location: true
    prefix: classpath:templates/
    suffix: .html
    mode: HTML
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3308/facebook
    username: root
    password: koreait
    driver-class-name: org.mariadb.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 30MB
      location: D:/springImg
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "875919437056-rh3np19943os9vpii98crn4hqkd274sh.apps.googleusercontent.com"
            client-secret: "5V4De6a79E0PfW2Aa_DQLMtp"
            scope:
              - profile
              - email
          facebook:
            client-id: 248745953463459
            client-secret: 54030a23563e5247ec031b2c908ef40e
            scope:
              - email
              - public_profile
          kakao:
            authorization-grant-type: authorization_code
            client-id:
            client-secret:
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - profile_nickname
              - profile_image
            client-authentication-method: POST
            client-name: Kakao
          naver:
            authorization-grant-type: authorization_code
            client-id: LDxu3BhL6x4w704G_x3a
            client-secret: cCMi8kjLld
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: name,email,profile_image
            client-name: Naver

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: properties
            # JSON 형태에서 "properties"라는 key값에 해당하는 value에 회원 정보가 담겨져있다.
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
            # JSON 형태에서 "response"라는 key값에 해당하는 value에 회원 정보가 담겨져있다.
mybatis:
  mapper-locations: mybatis-mapper/**/*.xml
  type-aliases-package: com.koreait.facebook

#톰캣 포트 변경
server:
  port: 8090