spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          startls:
            enable: true

  thymeleaf:
    check-template-location: true
    prefix: classpath:templates/
    suffix: .html
    mode: HTML
    cache: false

  datasource:
    url: jdbc:mysql://localhost:3308/facebook
    username: root
    password: koreait
    driver-class-name: org.mariadb.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
      location: D:/springImg

mybatis:
  mapper-location: mybatis-mapper/**/*.xml
  type-aliases-package: com.koreait.Homework

server:
  port: 8090