spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: splitcreed1760@gmail.com
    password: evjddiubfejuaqgi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  thymeleaf:
    check-template-location: true
    prefix: classpath:templates/
    suffix: .html
    mode: HTML
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/facebook
    username: root
    password: koreait
    driver-class-name: org.mariadb.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 30MB
      location: D:/springImg
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 909564357301-nefoeptb5isbavlg9gjrm9jc8g1hj0r7.apps.googleusercontent.com
            client-secret: lxxBAtomBaSw3rqjImrGVj3E
            scope:
              - profile
              - email
          facebook:
            client-id: 950071658903629
            client-secret: f0d3839485af42836dd68b8bd75291f5
            scope:
              - email
              - public_porofile
          kakao:
            authorization-grant-type: authorization_code
            #Rest Api 키값
            client-id: 7cae18818043ebd5454c14c68863977c
            #시큐리티 키 값
            client-secret: SK5OnOf4IzHZeHBPDQVtNPaNp8Ca1ODO
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            #내가 갖고싶은 범위
            scope:
              - profile_nikname
              - profile_image
            client-authentication-method: POST
            client-name: Kakao
          naver:
            authorization-grant-type: authorization_code
            client-id: jjE80mBGmPPu8kOYVJJP
            client-secret: 3EfhwvAMvF
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: name,profile_image
            client-name: Naver

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: properties
            # JSON 형태에서 "properties"라는 key값에 해당하는 value에 회원 정보가 담겨져있다.
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
            # JSON 형태에서 "response"라는 key값에 해당하는 value에 회원 정보가 담겨져있다.
mybatis:
  mapper-locations: mybatis-mapper/**/*.xml
  type-aliases-package: com.koreait.facebook


#톰캣 포트 변경
server:
  port: 8090